[package]
name = "ordo-scriptorum"
authors = ["zoop_potato <zooppotato@gmail.com>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
rsa = "0.9.2"
